### ISSUE TITLE
[Task] Machine-processable automated analysis results

### ISSUE THREAD

**Issue by andrewazores** [cryostatio/cryostat-reports#23]
Depends on https://github.com/cryostatio/cryostat/issues/880

When cryostat supports a JSON response format for automated analysis, the reports sidecar must also support the same for deployments where cryostat delegates requests rather than forking a subprocess.

**Comment by maxcao13** [comment]
As for this issue, does this need a separate endpoint? 

getReport at the /report endpoint is supposed to return a String, and since it's internal to cryostat does it make sense to have another endpoint (e.g. at /reportEval) for the Map/JSON RuleEvaluation object that returns the Map instead of the String?

**Comment by andrewazores** [comment]
Ideally it would still be the same endpoint and use the same `Accept`/`Content-Type` headers as previously described. Probably worth doing some reading on the `@Produces`/`@Consumes` annotations you see in that implementation.
